### ISSUE TITLE
Netlify

### ISSUE THREAD

**Issue by ShKlinkenberg** [Werkgroep-Toetsen-Op-Afstand/toetsweb#1]
@pieterbikkel waarom netlyfy if we can host directle from the github repo?

**Comment by pieterbikkel** [comment]
Met Netlify hebben we meer ervaring binnen B302 en GitHub pages geeft nog wel eens problemen met het hosten van React websites. Netlify is daarin tegen gratis en heeft continuous integration waarbij je iets aanpast in bijvoobeeld de productie branch het meteen wordt doorgevoerd naar de website die wordt gehost door Netlify.

**Comment by ShKlinkenberg** [comment]
Prima, ik heb netlify toegevoegd. Ik heb er verder geen ervaring mee. Heb je nu genoeg rechten om het in te richten? Heb je nog iets van mij nodig?

From: Pieter Bikkel ***@***.***>
Date: Monday, 19 December 2022 at 12:34
To: Werkgroep-Toetsen-Op-Afstand/toetsweb ***@***.***>
Cc: Sharon Klinkenberg ***@***.***>, Author ***@***.***>
Subject: Re: [Werkgroep-Toetsen-Op-Afstand/toetsweb] Netlify (Issue #1)

Met Netlify hebben we meer ervaring binnen B302 en GitHub pages geeft nog wel eens problemen met het hosten van React websites. Netlify is daarin tegen gratis en heeft continuous integration waarbij je iets aanpast in bijvoobeeld de productie branch het meteen wordt doorgevoerd naar de website die wordt gehost door Netlify.
